### ISSUE TITLE
Ability to use fallback

### ISSUE THREAD

**Issue by davidhouweling** [teambition/smart-limiter#1]
I'm presently looking at using smart-limiter (due to the use of thunk-redis with cluster mode), but we would also like to have the ability to fallback to another storage medium if we experience issues with redis (which we have in the past on other unrelated matter).

Do you have any suggestions as to how we could callback to say a local store (such as a memory one), or potentially just pause the limiter if redis cannot be reached (with appropriate `on` events)?

I was looking at express-brute as it is more popular, but the lack of redis cluster mode made me look to using this.

**Comment by zensh** [comment]
if redis cannot be reached, the redis client will emit some error, but it will take dozens of seconds. It means that if your application need a redis as distribution status store, you should keep redis healthy.
